### ISSUE TITLE
Will it work as scr file for windows 10?

### ISSUE THREAD

**Issue by eslamsidereel** [xbmc/screensaver.stars#17]
This is not an actual issue, but I've been using this screensaver in Kodi for a long time and i love it so much. 
I wanted to ask if the addon can be compiled as scr file for windows 10? I searched a lot for a starfield screensaver like this but could find anything that awesome. I hope that can be done.

**Comment by AlwinEsch** [comment]
Sorry for the late comment.

Not really, it's designed for the interface to Kodi.

However, the DirectX code or GL code could be taken over and used on a newly created and programmed Windows screensaver.

So in principle that would be possible, then you only need one who does it.

Since this is not directly related to Kodi I have to close the issue unfortunately, sorry therefore.
